---
apiVersion: v1
kind: Namespace
metadata:
  name: minions

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minions
data:
  MINIO_ROOT_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
type: Opaque
data:
  # rootroot
  MINIO_ROOT_PASSWORD: cm9vdHJvb3Q=